# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contract_create.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hedera.util.proto_pb import basic_types_pb2 as basic__types__pb2
from hedera.util.proto_pb import duration_pb2 as duration__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="contract_create.proto",
    package="proto",
    syntax="proto3",
    serialized_options=b'\n"com.hederahashgraph.api.proto.javaP\001',
    serialized_pb=b'\n\x15\x63ontract_create.proto\x12\x05proto\x1a\x11\x62\x61sic_types.proto\x1a\x0e\x64uration.proto"\xdf\x04\n\x1d\x43ontractCreateTransactionBody\x12\x1f\n\x06\x66ileID\x18\x01 \x01(\x0b\x32\r.proto.FileIDH\x00\x12\x12\n\x08initcode\x18\x10 \x01(\x0cH\x00\x12\x1c\n\x08\x61\x64minKey\x18\x03 \x01(\x0b\x32\n.proto.Key\x12\x0b\n\x03gas\x18\x04 \x01(\x03\x12\x16\n\x0einitialBalance\x18\x05 \x01(\x03\x12,\n\x0eproxyAccountID\x18\x06 \x01(\x0b\x32\x10.proto.AccountIDB\x02\x18\x01\x12(\n\x0f\x61utoRenewPeriod\x18\x08 \x01(\x0b\x32\x0f.proto.Duration\x12\x1d\n\x15\x63onstructorParameters\x18\t \x01(\x0c\x12\x1f\n\x07shardID\x18\n \x01(\x0b\x32\x0e.proto.ShardID\x12\x1f\n\x07realmID\x18\x0b \x01(\x0b\x32\x0e.proto.RealmID\x12$\n\x10newRealmAdminKey\x18\x0c \x01(\x0b\x32\n.proto.Key\x12\x0c\n\x04memo\x18\r \x01(\t\x12(\n max_automatic_token_associations\x18\x0e \x01(\x05\x12/\n\x15\x61uto_renew_account_id\x18\x0f \x01(\x0b\x32\x10.proto.AccountID\x12-\n\x11staked_account_id\x18\x11 \x01(\x0b\x32\x10.proto.AccountIDH\x01\x12\x18\n\x0estaked_node_id\x18\x12 \x01(\x03H\x01\x12\x16\n\x0e\x64\x65\x63line_reward\x18\x13 \x01(\x08\x42\x10\n\x0einitcodeSourceB\x0b\n\tstaked_idB&\n"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3',
    dependencies=[
        basic__types__pb2.DESCRIPTOR,
        duration__pb2.DESCRIPTOR,
    ],
)


_CONTRACTCREATETRANSACTIONBODY = _descriptor.Descriptor(
    name="ContractCreateTransactionBody",
    full_name="proto.ContractCreateTransactionBody",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="fileID",
            full_name="proto.ContractCreateTransactionBody.fileID",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="initcode",
            full_name="proto.ContractCreateTransactionBody.initcode",
            index=1,
            number=16,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="adminKey",
            full_name="proto.ContractCreateTransactionBody.adminKey",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="gas",
            full_name="proto.ContractCreateTransactionBody.gas",
            index=3,
            number=4,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="initialBalance",
            full_name="proto.ContractCreateTransactionBody.initialBalance",
            index=4,
            number=5,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="proxyAccountID",
            full_name="proto.ContractCreateTransactionBody.proxyAccountID",
            index=5,
            number=6,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=b"\030\001",
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="autoRenewPeriod",
            full_name="proto.ContractCreateTransactionBody.autoRenewPeriod",
            index=6,
            number=8,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="constructorParameters",
            full_name="proto.ContractCreateTransactionBody.constructorParameters",
            index=7,
            number=9,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="shardID",
            full_name="proto.ContractCreateTransactionBody.shardID",
            index=8,
            number=10,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="realmID",
            full_name="proto.ContractCreateTransactionBody.realmID",
            index=9,
            number=11,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="newRealmAdminKey",
            full_name="proto.ContractCreateTransactionBody.newRealmAdminKey",
            index=10,
            number=12,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="memo",
            full_name="proto.ContractCreateTransactionBody.memo",
            index=11,
            number=13,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="max_automatic_token_associations",
            full_name="proto.ContractCreateTransactionBody.max_automatic_token_associations",
            index=12,
            number=14,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="auto_renew_account_id",
            full_name="proto.ContractCreateTransactionBody.auto_renew_account_id",
            index=13,
            number=15,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="staked_account_id",
            full_name="proto.ContractCreateTransactionBody.staked_account_id",
            index=14,
            number=17,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="staked_node_id",
            full_name="proto.ContractCreateTransactionBody.staked_node_id",
            index=15,
            number=18,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="decline_reward",
            full_name="proto.ContractCreateTransactionBody.decline_reward",
            index=16,
            number=19,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="initcodeSource",
            full_name="proto.ContractCreateTransactionBody.initcodeSource",
            index=0,
            containing_type=None,
            fields=[],
        ),
        _descriptor.OneofDescriptor(
            name="staked_id",
            full_name="proto.ContractCreateTransactionBody.staked_id",
            index=1,
            containing_type=None,
            fields=[],
        ),
    ],
    serialized_start=68,
    serialized_end=675,
)

_CONTRACTCREATETRANSACTIONBODY.fields_by_name["fileID"].message_type = basic__types__pb2._FILEID
_CONTRACTCREATETRANSACTIONBODY.fields_by_name["adminKey"].message_type = basic__types__pb2._KEY
_CONTRACTCREATETRANSACTIONBODY.fields_by_name["proxyAccountID"].message_type = basic__types__pb2._ACCOUNTID
_CONTRACTCREATETRANSACTIONBODY.fields_by_name["autoRenewPeriod"].message_type = duration__pb2._DURATION
_CONTRACTCREATETRANSACTIONBODY.fields_by_name["shardID"].message_type = basic__types__pb2._SHARDID
_CONTRACTCREATETRANSACTIONBODY.fields_by_name["realmID"].message_type = basic__types__pb2._REALMID
_CONTRACTCREATETRANSACTIONBODY.fields_by_name["newRealmAdminKey"].message_type = basic__types__pb2._KEY
_CONTRACTCREATETRANSACTIONBODY.fields_by_name["auto_renew_account_id"].message_type = basic__types__pb2._ACCOUNTID
_CONTRACTCREATETRANSACTIONBODY.fields_by_name["staked_account_id"].message_type = basic__types__pb2._ACCOUNTID
_CONTRACTCREATETRANSACTIONBODY.oneofs_by_name["initcodeSource"].fields.append(
    _CONTRACTCREATETRANSACTIONBODY.fields_by_name["fileID"]
)
_CONTRACTCREATETRANSACTIONBODY.fields_by_name["fileID"].containing_oneof = _CONTRACTCREATETRANSACTIONBODY.oneofs_by_name[
    "initcodeSource"
]
_CONTRACTCREATETRANSACTIONBODY.oneofs_by_name["initcodeSource"].fields.append(
    _CONTRACTCREATETRANSACTIONBODY.fields_by_name["initcode"]
)
_CONTRACTCREATETRANSACTIONBODY.fields_by_name[
    "initcode"
].containing_oneof = _CONTRACTCREATETRANSACTIONBODY.oneofs_by_name["initcodeSource"]
_CONTRACTCREATETRANSACTIONBODY.oneofs_by_name["staked_id"].fields.append(
    _CONTRACTCREATETRANSACTIONBODY.fields_by_name["staked_account_id"]
)
_CONTRACTCREATETRANSACTIONBODY.fields_by_name[
    "staked_account_id"
].containing_oneof = _CONTRACTCREATETRANSACTIONBODY.oneofs_by_name["staked_id"]
_CONTRACTCREATETRANSACTIONBODY.oneofs_by_name["staked_id"].fields.append(
    _CONTRACTCREATETRANSACTIONBODY.fields_by_name["staked_node_id"]
)
_CONTRACTCREATETRANSACTIONBODY.fields_by_name[
    "staked_node_id"
].containing_oneof = _CONTRACTCREATETRANSACTIONBODY.oneofs_by_name["staked_id"]
DESCRIPTOR.message_types_by_name["ContractCreateTransactionBody"] = _CONTRACTCREATETRANSACTIONBODY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ContractCreateTransactionBody = _reflection.GeneratedProtocolMessageType(
    "ContractCreateTransactionBody",
    (_message.Message,),
    {
        "DESCRIPTOR": _CONTRACTCREATETRANSACTIONBODY,
        "__module__": "contract_create_pb2"
        # @@protoc_insertion_point(class_scope:proto.ContractCreateTransactionBody)
    },
)
_sym_db.RegisterMessage(ContractCreateTransactionBody)


DESCRIPTOR._options = None
_CONTRACTCREATETRANSACTIONBODY.fields_by_name["proxyAccountID"]._options = None
# @@protoc_insertion_point(module_scope)
