# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crypto_delete_allowance.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hedera.util.proto_pb import basic_types_pb2 as basic__types__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="crypto_delete_allowance.proto",
    package="proto",
    syntax="proto3",
    serialized_options=b'\n"com.hederahashgraph.api.proto.javaP\001',
    serialized_pb=b'\n\x1d\x63rypto_delete_allowance.proto\x12\x05proto\x1a\x11\x62\x61sic_types.proto"X\n$CryptoDeleteAllowanceTransactionBody\x12\x30\n\rnftAllowances\x18\x02 \x03(\x0b\x32\x19.proto.NftRemoveAllowance"o\n\x12NftRemoveAllowance\x12 \n\x08token_id\x18\x01 \x01(\x0b\x32\x0e.proto.TokenID\x12\x1f\n\x05owner\x18\x02 \x01(\x0b\x32\x10.proto.AccountID\x12\x16\n\x0eserial_numbers\x18\x03 \x03(\x03\x42&\n"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3',
    dependencies=[
        basic__types__pb2.DESCRIPTOR,
    ],
)


_CRYPTODELETEALLOWANCETRANSACTIONBODY = _descriptor.Descriptor(
    name="CryptoDeleteAllowanceTransactionBody",
    full_name="proto.CryptoDeleteAllowanceTransactionBody",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="nftAllowances",
            full_name="proto.CryptoDeleteAllowanceTransactionBody.nftAllowances",
            index=0,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=59,
    serialized_end=147,
)


_NFTREMOVEALLOWANCE = _descriptor.Descriptor(
    name="NftRemoveAllowance",
    full_name="proto.NftRemoveAllowance",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="token_id",
            full_name="proto.NftRemoveAllowance.token_id",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="owner",
            full_name="proto.NftRemoveAllowance.owner",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="serial_numbers",
            full_name="proto.NftRemoveAllowance.serial_numbers",
            index=2,
            number=3,
            type=3,
            cpp_type=2,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=149,
    serialized_end=260,
)

_CRYPTODELETEALLOWANCETRANSACTIONBODY.fields_by_name["nftAllowances"].message_type = _NFTREMOVEALLOWANCE
_NFTREMOVEALLOWANCE.fields_by_name["token_id"].message_type = basic__types__pb2._TOKENID
_NFTREMOVEALLOWANCE.fields_by_name["owner"].message_type = basic__types__pb2._ACCOUNTID
DESCRIPTOR.message_types_by_name["CryptoDeleteAllowanceTransactionBody"] = _CRYPTODELETEALLOWANCETRANSACTIONBODY
DESCRIPTOR.message_types_by_name["NftRemoveAllowance"] = _NFTREMOVEALLOWANCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CryptoDeleteAllowanceTransactionBody = _reflection.GeneratedProtocolMessageType(
    "CryptoDeleteAllowanceTransactionBody",
    (_message.Message,),
    {
        "DESCRIPTOR": _CRYPTODELETEALLOWANCETRANSACTIONBODY,
        "__module__": "crypto_delete_allowance_pb2"
        # @@protoc_insertion_point(class_scope:proto.CryptoDeleteAllowanceTransactionBody)
    },
)
_sym_db.RegisterMessage(CryptoDeleteAllowanceTransactionBody)

NftRemoveAllowance = _reflection.GeneratedProtocolMessageType(
    "NftRemoveAllowance",
    (_message.Message,),
    {
        "DESCRIPTOR": _NFTREMOVEALLOWANCE,
        "__module__": "crypto_delete_allowance_pb2"
        # @@protoc_insertion_point(class_scope:proto.NftRemoveAllowance)
    },
)
_sym_db.RegisterMessage(NftRemoveAllowance)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
