# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crypto_approve_allowance.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2

from hedera.util.proto_pb import basic_types_pb2 as basic__types__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="crypto_approve_allowance.proto",
    package="proto",
    syntax="proto3",
    serialized_options=b'\n"com.hederahashgraph.api.proto.javaP\001',
    serialized_pb=b'\n\x1e\x63rypto_approve_allowance.proto\x12\x05proto\x1a\x11\x62\x61sic_types.proto\x1a\x1egoogle/protobuf/wrappers.proto"\xb5\x01\n%CryptoApproveAllowanceTransactionBody\x12\x30\n\x10\x63ryptoAllowances\x18\x01 \x03(\x0b\x32\x16.proto.CryptoAllowance\x12*\n\rnftAllowances\x18\x02 \x03(\x0b\x32\x13.proto.NftAllowance\x12.\n\x0ftokenAllowances\x18\x03 \x03(\x0b\x32\x15.proto.TokenAllowance"e\n\x0f\x43ryptoAllowance\x12\x1f\n\x05owner\x18\x01 \x01(\x0b\x32\x10.proto.AccountID\x12!\n\x07spender\x18\x02 \x01(\x0b\x32\x10.proto.AccountID\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x03"\xef\x01\n\x0cNftAllowance\x12\x1f\n\x07tokenId\x18\x01 \x01(\x0b\x32\x0e.proto.TokenID\x12\x1f\n\x05owner\x18\x02 \x01(\x0b\x32\x10.proto.AccountID\x12!\n\x07spender\x18\x03 \x01(\x0b\x32\x10.proto.AccountID\x12\x16\n\x0eserial_numbers\x18\x04 \x03(\x03\x12\x34\n\x10\x61pproved_for_all\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12,\n\x12\x64\x65legating_spender\x18\x06 \x01(\x0b\x32\x10.proto.AccountID"\x85\x01\n\x0eTokenAllowance\x12\x1f\n\x07tokenId\x18\x01 \x01(\x0b\x32\x0e.proto.TokenID\x12\x1f\n\x05owner\x18\x02 \x01(\x0b\x32\x10.proto.AccountID\x12!\n\x07spender\x18\x03 \x01(\x0b\x32\x10.proto.AccountID\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x03\x42&\n"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3',
    dependencies=[
        basic__types__pb2.DESCRIPTOR,
        google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,
    ],
)


_CRYPTOAPPROVEALLOWANCETRANSACTIONBODY = _descriptor.Descriptor(
    name="CryptoApproveAllowanceTransactionBody",
    full_name="proto.CryptoApproveAllowanceTransactionBody",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="cryptoAllowances",
            full_name="proto.CryptoApproveAllowanceTransactionBody.cryptoAllowances",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="nftAllowances",
            full_name="proto.CryptoApproveAllowanceTransactionBody.nftAllowances",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="tokenAllowances",
            full_name="proto.CryptoApproveAllowanceTransactionBody.tokenAllowances",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=93,
    serialized_end=274,
)


_CRYPTOALLOWANCE = _descriptor.Descriptor(
    name="CryptoAllowance",
    full_name="proto.CryptoAllowance",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="owner",
            full_name="proto.CryptoAllowance.owner",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="spender",
            full_name="proto.CryptoAllowance.spender",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="amount",
            full_name="proto.CryptoAllowance.amount",
            index=2,
            number=3,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=276,
    serialized_end=377,
)


_NFTALLOWANCE = _descriptor.Descriptor(
    name="NftAllowance",
    full_name="proto.NftAllowance",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="tokenId",
            full_name="proto.NftAllowance.tokenId",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="owner",
            full_name="proto.NftAllowance.owner",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="spender",
            full_name="proto.NftAllowance.spender",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="serial_numbers",
            full_name="proto.NftAllowance.serial_numbers",
            index=3,
            number=4,
            type=3,
            cpp_type=2,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="approved_for_all",
            full_name="proto.NftAllowance.approved_for_all",
            index=4,
            number=5,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="delegating_spender",
            full_name="proto.NftAllowance.delegating_spender",
            index=5,
            number=6,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=380,
    serialized_end=619,
)


_TOKENALLOWANCE = _descriptor.Descriptor(
    name="TokenAllowance",
    full_name="proto.TokenAllowance",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="tokenId",
            full_name="proto.TokenAllowance.tokenId",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="owner",
            full_name="proto.TokenAllowance.owner",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="spender",
            full_name="proto.TokenAllowance.spender",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="amount",
            full_name="proto.TokenAllowance.amount",
            index=3,
            number=4,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=622,
    serialized_end=755,
)

_CRYPTOAPPROVEALLOWANCETRANSACTIONBODY.fields_by_name["cryptoAllowances"].message_type = _CRYPTOALLOWANCE
_CRYPTOAPPROVEALLOWANCETRANSACTIONBODY.fields_by_name["nftAllowances"].message_type = _NFTALLOWANCE
_CRYPTOAPPROVEALLOWANCETRANSACTIONBODY.fields_by_name["tokenAllowances"].message_type = _TOKENALLOWANCE
_CRYPTOALLOWANCE.fields_by_name["owner"].message_type = basic__types__pb2._ACCOUNTID
_CRYPTOALLOWANCE.fields_by_name["spender"].message_type = basic__types__pb2._ACCOUNTID
_NFTALLOWANCE.fields_by_name["tokenId"].message_type = basic__types__pb2._TOKENID
_NFTALLOWANCE.fields_by_name["owner"].message_type = basic__types__pb2._ACCOUNTID
_NFTALLOWANCE.fields_by_name["spender"].message_type = basic__types__pb2._ACCOUNTID
_NFTALLOWANCE.fields_by_name["approved_for_all"].message_type = google_dot_protobuf_dot_wrappers__pb2._BOOLVALUE
_NFTALLOWANCE.fields_by_name["delegating_spender"].message_type = basic__types__pb2._ACCOUNTID
_TOKENALLOWANCE.fields_by_name["tokenId"].message_type = basic__types__pb2._TOKENID
_TOKENALLOWANCE.fields_by_name["owner"].message_type = basic__types__pb2._ACCOUNTID
_TOKENALLOWANCE.fields_by_name["spender"].message_type = basic__types__pb2._ACCOUNTID
DESCRIPTOR.message_types_by_name["CryptoApproveAllowanceTransactionBody"] = _CRYPTOAPPROVEALLOWANCETRANSACTIONBODY
DESCRIPTOR.message_types_by_name["CryptoAllowance"] = _CRYPTOALLOWANCE
DESCRIPTOR.message_types_by_name["NftAllowance"] = _NFTALLOWANCE
DESCRIPTOR.message_types_by_name["TokenAllowance"] = _TOKENALLOWANCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CryptoApproveAllowanceTransactionBody = _reflection.GeneratedProtocolMessageType(
    "CryptoApproveAllowanceTransactionBody",
    (_message.Message,),
    {
        "DESCRIPTOR": _CRYPTOAPPROVEALLOWANCETRANSACTIONBODY,
        "__module__": "crypto_approve_allowance_pb2"
        # @@protoc_insertion_point(class_scope:proto.CryptoApproveAllowanceTransactionBody)
    },
)
_sym_db.RegisterMessage(CryptoApproveAllowanceTransactionBody)

CryptoAllowance = _reflection.GeneratedProtocolMessageType(
    "CryptoAllowance",
    (_message.Message,),
    {
        "DESCRIPTOR": _CRYPTOALLOWANCE,
        "__module__": "crypto_approve_allowance_pb2"
        # @@protoc_insertion_point(class_scope:proto.CryptoAllowance)
    },
)
_sym_db.RegisterMessage(CryptoAllowance)

NftAllowance = _reflection.GeneratedProtocolMessageType(
    "NftAllowance",
    (_message.Message,),
    {
        "DESCRIPTOR": _NFTALLOWANCE,
        "__module__": "crypto_approve_allowance_pb2"
        # @@protoc_insertion_point(class_scope:proto.NftAllowance)
    },
)
_sym_db.RegisterMessage(NftAllowance)

TokenAllowance = _reflection.GeneratedProtocolMessageType(
    "TokenAllowance",
    (_message.Message,),
    {
        "DESCRIPTOR": _TOKENALLOWANCE,
        "__module__": "crypto_approve_allowance_pb2"
        # @@protoc_insertion_point(class_scope:proto.TokenAllowance)
    },
)
_sym_db.RegisterMessage(TokenAllowance)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
