# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hash_object.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import enum_type_wrapper

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="hash_object.proto",
    package="proto",
    syntax="proto3",
    serialized_options=b"\n com.hedera.services.stream.protoP\001",
    serialized_pb=b"\n\x11hash_object.proto\x12\x05proto\"S\n\nHashObject\x12'\n\talgorithm\x18\x01 \x01(\x0e\x32\x14.proto.HashAlgorithm\x12\x0e\n\x06length\x18\x02 \x01(\x05\x12\x0c\n\x04hash\x18\x03 \x01(\x0c*8\n\rHashAlgorithm\x12\x1a\n\x16HASH_ALGORITHM_UNKNOWN\x10\x00\x12\x0b\n\x07SHA_384\x10\x01\x42$\n com.hedera.services.stream.protoP\x01\x62\x06proto3",
)

_HASHALGORITHM = _descriptor.EnumDescriptor(
    name="HashAlgorithm",
    full_name="proto.HashAlgorithm",
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name="HASH_ALGORITHM_UNKNOWN",
            index=0,
            number=0,
            serialized_options=None,
            type=None,
        ),
        _descriptor.EnumValueDescriptor(
            name="SHA_384",
            index=1,
            number=1,
            serialized_options=None,
            type=None,
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=113,
    serialized_end=169,
)
_sym_db.RegisterEnumDescriptor(_HASHALGORITHM)

HashAlgorithm = enum_type_wrapper.EnumTypeWrapper(_HASHALGORITHM)
HASH_ALGORITHM_UNKNOWN = 0
SHA_384 = 1


_HASHOBJECT = _descriptor.Descriptor(
    name="HashObject",
    full_name="proto.HashObject",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="algorithm",
            full_name="proto.HashObject.algorithm",
            index=0,
            number=1,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="length",
            full_name="proto.HashObject.length",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="hash",
            full_name="proto.HashObject.hash",
            index=2,
            number=3,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=28,
    serialized_end=111,
)

_HASHOBJECT.fields_by_name["algorithm"].enum_type = _HASHALGORITHM
DESCRIPTOR.message_types_by_name["HashObject"] = _HASHOBJECT
DESCRIPTOR.enum_types_by_name["HashAlgorithm"] = _HASHALGORITHM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HashObject = _reflection.GeneratedProtocolMessageType(
    "HashObject",
    (_message.Message,),
    {
        "DESCRIPTOR": _HASHOBJECT,
        "__module__": "hash_object_pb2"
        # @@protoc_insertion_point(class_scope:proto.HashObject)
    },
)
_sym_db.RegisterMessage(HashObject)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
