# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sidecar_file.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hedera.util.proto_pb import basic_types_pb2 as basic__types__pb2
from hedera.util.proto_pb import contract_call_local_pb2 as contract__call__local__pb2
from hedera.util.proto_pb import timestamp_pb2 as timestamp__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="sidecar_file.proto",
    package="proto",
    syntax="proto3",
    serialized_options=b"\n com.hedera.services.stream.protoP\001",
    serialized_pb=b'\n\x12sidecar_file.proto\x12\x05proto\x1a\x11\x62\x61sic_types.proto\x1a\x0ftimestamp.proto\x1a\x19\x63ontract_call_local.proto"G\n\x0bSidecarFile\x12\x38\n\x0fsidecar_records\x18\x01 \x03(\x0b\x32\x1f.proto.TransactionSidecarRecord"\x92\x01\n\x18TransactionSidecarRecord\x12-\n\x13\x63onsensus_timestamp\x18\x01 \x01(\x0b\x32\x10.proto.Timestamp\x12\x34\n\rstate_changes\x18\x02 \x01(\x0b\x32\x1b.proto.ContractStateChangesH\x00\x42\x11\n\x0fsidecar_records"R\n\x14\x43ontractStateChanges\x12:\n\x16\x63ontract_state_changes\x18\x01 \x03(\x0b\x32\x1a.proto.ContractStateChangeB$\n com.hedera.services.stream.protoP\x01\x62\x06proto3',
    dependencies=[
        basic__types__pb2.DESCRIPTOR,
        timestamp__pb2.DESCRIPTOR,
        contract__call__local__pb2.DESCRIPTOR,
    ],
)


_SIDECARFILE = _descriptor.Descriptor(
    name="SidecarFile",
    full_name="proto.SidecarFile",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="sidecar_records",
            full_name="proto.SidecarFile.sidecar_records",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=92,
    serialized_end=163,
)


_TRANSACTIONSIDECARRECORD = _descriptor.Descriptor(
    name="TransactionSidecarRecord",
    full_name="proto.TransactionSidecarRecord",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="consensus_timestamp",
            full_name="proto.TransactionSidecarRecord.consensus_timestamp",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="state_changes",
            full_name="proto.TransactionSidecarRecord.state_changes",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[
        _descriptor.OneofDescriptor(
            name="sidecar_records",
            full_name="proto.TransactionSidecarRecord.sidecar_records",
            index=0,
            containing_type=None,
            fields=[],
        ),
    ],
    serialized_start=166,
    serialized_end=312,
)


_CONTRACTSTATECHANGES = _descriptor.Descriptor(
    name="ContractStateChanges",
    full_name="proto.ContractStateChanges",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="contract_state_changes",
            full_name="proto.ContractStateChanges.contract_state_changes",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=314,
    serialized_end=396,
)

_SIDECARFILE.fields_by_name["sidecar_records"].message_type = _TRANSACTIONSIDECARRECORD
_TRANSACTIONSIDECARRECORD.fields_by_name["consensus_timestamp"].message_type = timestamp__pb2._TIMESTAMP
_TRANSACTIONSIDECARRECORD.fields_by_name["state_changes"].message_type = _CONTRACTSTATECHANGES
_TRANSACTIONSIDECARRECORD.oneofs_by_name["sidecar_records"].fields.append(
    _TRANSACTIONSIDECARRECORD.fields_by_name["state_changes"]
)
_TRANSACTIONSIDECARRECORD.fields_by_name["state_changes"].containing_oneof = _TRANSACTIONSIDECARRECORD.oneofs_by_name[
    "sidecar_records"
]
_CONTRACTSTATECHANGES.fields_by_name[
    "contract_state_changes"
].message_type = contract__call__local__pb2._CONTRACTSTATECHANGE
DESCRIPTOR.message_types_by_name["SidecarFile"] = _SIDECARFILE
DESCRIPTOR.message_types_by_name["TransactionSidecarRecord"] = _TRANSACTIONSIDECARRECORD
DESCRIPTOR.message_types_by_name["ContractStateChanges"] = _CONTRACTSTATECHANGES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SidecarFile = _reflection.GeneratedProtocolMessageType(
    "SidecarFile",
    (_message.Message,),
    {
        "DESCRIPTOR": _SIDECARFILE,
        "__module__": "sidecar_file_pb2"
        # @@protoc_insertion_point(class_scope:proto.SidecarFile)
    },
)
_sym_db.RegisterMessage(SidecarFile)

TransactionSidecarRecord = _reflection.GeneratedProtocolMessageType(
    "TransactionSidecarRecord",
    (_message.Message,),
    {
        "DESCRIPTOR": _TRANSACTIONSIDECARRECORD,
        "__module__": "sidecar_file_pb2"
        # @@protoc_insertion_point(class_scope:proto.TransactionSidecarRecord)
    },
)
_sym_db.RegisterMessage(TransactionSidecarRecord)

ContractStateChanges = _reflection.GeneratedProtocolMessageType(
    "ContractStateChanges",
    (_message.Message,),
    {
        "DESCRIPTOR": _CONTRACTSTATECHANGES,
        "__module__": "sidecar_file_pb2"
        # @@protoc_insertion_point(class_scope:proto.ContractStateChanges)
    },
)
_sym_db.RegisterMessage(ContractStateChanges)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
