# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signature_file.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import enum_type_wrapper

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hedera.util.proto_pb import basic_types_pb2 as basic__types__pb2
from hedera.util.proto_pb import hash_object_pb2 as hash__object__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="signature_file.proto",
    package="proto",
    syntax="proto3",
    serialized_options=b"\n com.hedera.services.stream.protoP\001",
    serialized_pb=b'\n\x14signature_file.proto\x12\x05proto\x1a\x11\x62\x61sic_types.proto\x1a\x11hash_object.proto"s\n\rSignatureFile\x12.\n\x0e\x66ile_signature\x18\x01 \x01(\x0b\x32\x16.proto.SignatureObject\x12\x32\n\x12metadata_signature\x18\x02 \x01(\x0b\x32\x16.proto.SignatureObject"\x92\x01\n\x0fSignatureObject\x12"\n\x04type\x18\x01 \x01(\x0e\x32\x14.proto.SignatureType\x12\x0e\n\x06length\x18\x02 \x01(\x05\x12\x10\n\x08\x63hecksum\x18\x03 \x01(\x05\x12\x11\n\tsignature\x18\x04 \x01(\x0c\x12&\n\x0bhash_object\x18\x05 \x01(\x0b\x32\x11.proto.HashObject*A\n\rSignatureType\x12\x1a\n\x16SIGNATURE_TYPE_UNKNOWN\x10\x00\x12\x14\n\x10SHA_384_WITH_RSA\x10\x01\x42$\n com.hedera.services.stream.protoP\x01\x62\x06proto3',
    dependencies=[
        basic__types__pb2.DESCRIPTOR,
        hash__object__pb2.DESCRIPTOR,
    ],
)

_SIGNATURETYPE = _descriptor.EnumDescriptor(
    name="SignatureType",
    full_name="proto.SignatureType",
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name="SIGNATURE_TYPE_UNKNOWN",
            index=0,
            number=0,
            serialized_options=None,
            type=None,
        ),
        _descriptor.EnumValueDescriptor(
            name="SHA_384_WITH_RSA",
            index=1,
            number=1,
            serialized_options=None,
            type=None,
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=335,
    serialized_end=400,
)
_sym_db.RegisterEnumDescriptor(_SIGNATURETYPE)

SignatureType = enum_type_wrapper.EnumTypeWrapper(_SIGNATURETYPE)
SIGNATURE_TYPE_UNKNOWN = 0
SHA_384_WITH_RSA = 1


_SIGNATUREFILE = _descriptor.Descriptor(
    name="SignatureFile",
    full_name="proto.SignatureFile",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="file_signature",
            full_name="proto.SignatureFile.file_signature",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="metadata_signature",
            full_name="proto.SignatureFile.metadata_signature",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=69,
    serialized_end=184,
)


_SIGNATUREOBJECT = _descriptor.Descriptor(
    name="SignatureObject",
    full_name="proto.SignatureObject",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="type",
            full_name="proto.SignatureObject.type",
            index=0,
            number=1,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="length",
            full_name="proto.SignatureObject.length",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="checksum",
            full_name="proto.SignatureObject.checksum",
            index=2,
            number=3,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="signature",
            full_name="proto.SignatureObject.signature",
            index=3,
            number=4,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="hash_object",
            full_name="proto.SignatureObject.hash_object",
            index=4,
            number=5,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=187,
    serialized_end=333,
)

_SIGNATUREFILE.fields_by_name["file_signature"].message_type = _SIGNATUREOBJECT
_SIGNATUREFILE.fields_by_name["metadata_signature"].message_type = _SIGNATUREOBJECT
_SIGNATUREOBJECT.fields_by_name["type"].enum_type = _SIGNATURETYPE
_SIGNATUREOBJECT.fields_by_name["hash_object"].message_type = hash__object__pb2._HASHOBJECT
DESCRIPTOR.message_types_by_name["SignatureFile"] = _SIGNATUREFILE
DESCRIPTOR.message_types_by_name["SignatureObject"] = _SIGNATUREOBJECT
DESCRIPTOR.enum_types_by_name["SignatureType"] = _SIGNATURETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SignatureFile = _reflection.GeneratedProtocolMessageType(
    "SignatureFile",
    (_message.Message,),
    {
        "DESCRIPTOR": _SIGNATUREFILE,
        "__module__": "signature_file_pb2"
        # @@protoc_insertion_point(class_scope:proto.SignatureFile)
    },
)
_sym_db.RegisterMessage(SignatureFile)

SignatureObject = _reflection.GeneratedProtocolMessageType(
    "SignatureObject",
    (_message.Message,),
    {
        "DESCRIPTOR": _SIGNATUREOBJECT,
        "__module__": "signature_file_pb2"
        # @@protoc_insertion_point(class_scope:proto.SignatureObject)
    },
)
_sym_db.RegisterMessage(SignatureObject)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
