# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crypto_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hedera.util.proto_pb import query_pb2 as query__pb2
from hedera.util.proto_pb import response_pb2 as response__pb2
from hedera.util.proto_pb import transaction_pb2 as transaction__pb2
from hedera.util.proto_pb import transaction_response_pb2 as transaction__response__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="crypto_service.proto",
    package="proto",
    syntax="proto3",
    serialized_options=b"\n&com.hederahashgraph.service.proto.java",
    serialized_pb=b"\n\x14\x63rypto_service.proto\x12\x05proto\x1a\x0bquery.proto\x1a\x0eresponse.proto\x1a\x1atransaction_response.proto\x1a\x11transaction.proto2\xc3\x07\n\rCryptoService\x12?\n\rcreateAccount\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12?\n\rupdateAccount\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12@\n\x0e\x63ryptoTransfer\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12>\n\x0c\x63ryptoDelete\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12\x43\n\x11\x61pproveAllowances\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12\x42\n\x10\x64\x65leteAllowances\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12=\n\x0b\x61\x64\x64LiveHash\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12@\n\x0e\x64\x65leteLiveHash\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12,\n\x0bgetLiveHash\x12\x0c.proto.Query\x1a\x0f.proto.Response\x12\x32\n\x11getAccountRecords\x12\x0c.proto.Query\x1a\x0f.proto.Response\x12\x31\n\x10\x63ryptoGetBalance\x12\x0c.proto.Query\x1a\x0f.proto.Response\x12/\n\x0egetAccountInfo\x12\x0c.proto.Query\x1a\x0f.proto.Response\x12\x37\n\x16getTransactionReceipts\x12\x0c.proto.Query\x1a\x0f.proto.Response\x12\x39\n\x18getFastTransactionRecord\x12\x0c.proto.Query\x1a\x0f.proto.Response\x12\x32\n\x11getTxRecordByTxID\x12\x0c.proto.Query\x1a\x0f.proto.Response\x12\x36\n\x15getStakersByAccountID\x12\x0c.proto.Query\x1a\x0f.proto.ResponseB(\n&com.hederahashgraph.service.proto.javab\x06proto3",
    dependencies=[
        query__pb2.DESCRIPTOR,
        response__pb2.DESCRIPTOR,
        transaction__response__pb2.DESCRIPTOR,
        transaction__pb2.DESCRIPTOR,
    ],
)


_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_CRYPTOSERVICE = _descriptor.ServiceDescriptor(
    name="CryptoService",
    full_name="proto.CryptoService",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=108,
    serialized_end=1071,
    methods=[
        _descriptor.MethodDescriptor(
            name="createAccount",
            full_name="proto.CryptoService.createAccount",
            index=0,
            containing_service=None,
            input_type=transaction__pb2._TRANSACTION,
            output_type=transaction__response__pb2._TRANSACTIONRESPONSE,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="updateAccount",
            full_name="proto.CryptoService.updateAccount",
            index=1,
            containing_service=None,
            input_type=transaction__pb2._TRANSACTION,
            output_type=transaction__response__pb2._TRANSACTIONRESPONSE,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="cryptoTransfer",
            full_name="proto.CryptoService.cryptoTransfer",
            index=2,
            containing_service=None,
            input_type=transaction__pb2._TRANSACTION,
            output_type=transaction__response__pb2._TRANSACTIONRESPONSE,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="cryptoDelete",
            full_name="proto.CryptoService.cryptoDelete",
            index=3,
            containing_service=None,
            input_type=transaction__pb2._TRANSACTION,
            output_type=transaction__response__pb2._TRANSACTIONRESPONSE,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="approveAllowances",
            full_name="proto.CryptoService.approveAllowances",
            index=4,
            containing_service=None,
            input_type=transaction__pb2._TRANSACTION,
            output_type=transaction__response__pb2._TRANSACTIONRESPONSE,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="deleteAllowances",
            full_name="proto.CryptoService.deleteAllowances",
            index=5,
            containing_service=None,
            input_type=transaction__pb2._TRANSACTION,
            output_type=transaction__response__pb2._TRANSACTIONRESPONSE,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="addLiveHash",
            full_name="proto.CryptoService.addLiveHash",
            index=6,
            containing_service=None,
            input_type=transaction__pb2._TRANSACTION,
            output_type=transaction__response__pb2._TRANSACTIONRESPONSE,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="deleteLiveHash",
            full_name="proto.CryptoService.deleteLiveHash",
            index=7,
            containing_service=None,
            input_type=transaction__pb2._TRANSACTION,
            output_type=transaction__response__pb2._TRANSACTIONRESPONSE,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="getLiveHash",
            full_name="proto.CryptoService.getLiveHash",
            index=8,
            containing_service=None,
            input_type=query__pb2._QUERY,
            output_type=response__pb2._RESPONSE,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="getAccountRecords",
            full_name="proto.CryptoService.getAccountRecords",
            index=9,
            containing_service=None,
            input_type=query__pb2._QUERY,
            output_type=response__pb2._RESPONSE,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="cryptoGetBalance",
            full_name="proto.CryptoService.cryptoGetBalance",
            index=10,
            containing_service=None,
            input_type=query__pb2._QUERY,
            output_type=response__pb2._RESPONSE,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="getAccountInfo",
            full_name="proto.CryptoService.getAccountInfo",
            index=11,
            containing_service=None,
            input_type=query__pb2._QUERY,
            output_type=response__pb2._RESPONSE,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="getTransactionReceipts",
            full_name="proto.CryptoService.getTransactionReceipts",
            index=12,
            containing_service=None,
            input_type=query__pb2._QUERY,
            output_type=response__pb2._RESPONSE,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="getFastTransactionRecord",
            full_name="proto.CryptoService.getFastTransactionRecord",
            index=13,
            containing_service=None,
            input_type=query__pb2._QUERY,
            output_type=response__pb2._RESPONSE,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="getTxRecordByTxID",
            full_name="proto.CryptoService.getTxRecordByTxID",
            index=14,
            containing_service=None,
            input_type=query__pb2._QUERY,
            output_type=response__pb2._RESPONSE,
            serialized_options=None,
        ),
        _descriptor.MethodDescriptor(
            name="getStakersByAccountID",
            full_name="proto.CryptoService.getStakersByAccountID",
            index=15,
            containing_service=None,
            input_type=query__pb2._QUERY,
            output_type=response__pb2._RESPONSE,
            serialized_options=None,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_CRYPTOSERVICE)

DESCRIPTOR.services_by_name["CryptoService"] = _CRYPTOSERVICE

# @@protoc_insertion_point(module_scope)
