# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethereum_transaction.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hedera.util.proto_pb import basic_types_pb2 as basic__types__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="ethereum_transaction.proto",
    package="proto",
    syntax="proto3",
    serialized_options=b'\n"com.hederahashgraph.api.proto.javaP\001',
    serialized_pb=b'\n\x1a\x65thereum_transaction.proto\x12\x05proto\x1a\x11\x62\x61sic_types.proto"m\n\x17\x45thereumTransactionBody\x12\x15\n\rethereum_data\x18\x01 \x01(\x0c\x12 \n\tcall_data\x18\x02 \x01(\x0b\x32\r.proto.FileID\x12\x19\n\x11max_gas_allowance\x18\x03 \x01(\x03\x42&\n"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3',
    dependencies=[
        basic__types__pb2.DESCRIPTOR,
    ],
)


_ETHEREUMTRANSACTIONBODY = _descriptor.Descriptor(
    name="EthereumTransactionBody",
    full_name="proto.EthereumTransactionBody",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="ethereum_data",
            full_name="proto.EthereumTransactionBody.ethereum_data",
            index=0,
            number=1,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="call_data",
            full_name="proto.EthereumTransactionBody.call_data",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="max_gas_allowance",
            full_name="proto.EthereumTransactionBody.max_gas_allowance",
            index=2,
            number=3,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=56,
    serialized_end=165,
)

_ETHEREUMTRANSACTIONBODY.fields_by_name["call_data"].message_type = basic__types__pb2._FILEID
DESCRIPTOR.message_types_by_name["EthereumTransactionBody"] = _ETHEREUMTRANSACTIONBODY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EthereumTransactionBody = _reflection.GeneratedProtocolMessageType(
    "EthereumTransactionBody",
    (_message.Message,),
    {
        "DESCRIPTOR": _ETHEREUMTRANSACTIONBODY,
        "__module__": "ethereum_transaction_pb2"
        # @@protoc_insertion_point(class_scope:proto.EthereumTransactionBody)
    },
)
_sym_db.RegisterMessage(EthereumTransactionBody)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
