# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mirror_network_service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hedera.util.proto_pb import basic_types_pb2 as basic__types__pb2
from hedera.util.proto_pb import timestamp_pb2 as timestamp__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="mirror_network_service.proto",
    package="com.hedera.mirror.api.proto",
    syntax="proto3",
    serialized_options=b"\n\033com.hedera.mirror.api.protoP\001",
    serialized_pb=b'\n\x1cmirror_network_service.proto\x12\x1b\x63om.hedera.mirror.api.proto\x1a\x11\x62\x61sic_types.proto\x1a\x0ftimestamp.proto"A\n\x10\x41\x64\x64ressBookQuery\x12\x1e\n\x07\x66ile_id\x18\x01 \x01(\x0b\x32\r.proto.FileID\x12\r\n\x05limit\x18\x02 \x01(\x05\x32\x61\n\x0eNetworkService\x12O\n\x08getNodes\x12-.com.hedera.mirror.api.proto.AddressBookQuery\x1a\x12.proto.NodeAddress0\x01\x42\x1f\n\x1b\x63om.hedera.mirror.api.protoP\x01\x62\x06proto3',
    dependencies=[
        basic__types__pb2.DESCRIPTOR,
        timestamp__pb2.DESCRIPTOR,
    ],
)


_ADDRESSBOOKQUERY = _descriptor.Descriptor(
    name="AddressBookQuery",
    full_name="com.hedera.mirror.api.proto.AddressBookQuery",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="file_id",
            full_name="com.hedera.mirror.api.proto.AddressBookQuery.file_id",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="limit",
            full_name="com.hedera.mirror.api.proto.AddressBookQuery.limit",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=97,
    serialized_end=162,
)

_ADDRESSBOOKQUERY.fields_by_name["file_id"].message_type = basic__types__pb2._FILEID
DESCRIPTOR.message_types_by_name["AddressBookQuery"] = _ADDRESSBOOKQUERY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddressBookQuery = _reflection.GeneratedProtocolMessageType(
    "AddressBookQuery",
    (_message.Message,),
    {
        "DESCRIPTOR": _ADDRESSBOOKQUERY,
        "__module__": "mirror_network_service_pb2"
        # @@protoc_insertion_point(class_scope:com.hedera.mirror.api.proto.AddressBookQuery)
    },
)
_sym_db.RegisterMessage(AddressBookQuery)


DESCRIPTOR._options = None

_NETWORKSERVICE = _descriptor.ServiceDescriptor(
    name="NetworkService",
    full_name="com.hedera.mirror.api.proto.NetworkService",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=164,
    serialized_end=261,
    methods=[
        _descriptor.MethodDescriptor(
            name="getNodes",
            full_name="com.hedera.mirror.api.proto.NetworkService.getNodes",
            index=0,
            containing_service=None,
            input_type=_ADDRESSBOOKQUERY,
            output_type=basic__types__pb2._NODEADDRESS,
            serialized_options=None,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_NETWORKSERVICE)

DESCRIPTOR.services_by_name["NetworkService"] = _NETWORKSERVICE

# @@protoc_insertion_point(module_scope)
