# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node_stake_update.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from hedera.util.proto_pb import basic_types_pb2 as basic__types__pb2
from hedera.util.proto_pb import timestamp_pb2 as timestamp__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="node_stake_update.proto",
    package="proto",
    syntax="proto3",
    serialized_options=b'\n"com.hederahashgraph.api.proto.javaP\001',
    serialized_pb=b'\n\x17node_stake_update.proto\x12\x05proto\x1a\x11\x62\x61sic_types.proto\x1a\x0ftimestamp.proto"w\n\x1eNodeStakeUpdateTransactionBody\x12/\n\x15\x65nd_of_staking_period\x18\x01 \x01(\x0b\x32\x10.proto.Timestamp\x12$\n\nnode_stake\x18\x02 \x03(\x0b\x32\x10.proto.NodeStake"\x9a\x01\n\tNodeStake\x12\x11\n\tmax_stake\x18\x01 \x01(\x03\x12\x11\n\tmin_stake\x18\x02 \x01(\x03\x12\x0f\n\x07node_id\x18\x03 \x01(\x03\x12\x13\n\x0breward_rate\x18\x04 \x01(\x03\x12\r\n\x05stake\x18\x05 \x01(\x03\x12\x1a\n\x12stake_not_rewarded\x18\x06 \x01(\x03\x12\x16\n\x0estake_rewarded\x18\x07 \x01(\x03\x42&\n"com.hederahashgraph.api.proto.javaP\x01\x62\x06proto3',
    dependencies=[
        basic__types__pb2.DESCRIPTOR,
        timestamp__pb2.DESCRIPTOR,
    ],
)


_NODESTAKEUPDATETRANSACTIONBODY = _descriptor.Descriptor(
    name="NodeStakeUpdateTransactionBody",
    full_name="proto.NodeStakeUpdateTransactionBody",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="end_of_staking_period",
            full_name="proto.NodeStakeUpdateTransactionBody.end_of_staking_period",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="node_stake",
            full_name="proto.NodeStakeUpdateTransactionBody.node_stake",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=70,
    serialized_end=189,
)


_NODESTAKE = _descriptor.Descriptor(
    name="NodeStake",
    full_name="proto.NodeStake",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="max_stake",
            full_name="proto.NodeStake.max_stake",
            index=0,
            number=1,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="min_stake",
            full_name="proto.NodeStake.min_stake",
            index=1,
            number=2,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="node_id",
            full_name="proto.NodeStake.node_id",
            index=2,
            number=3,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="reward_rate",
            full_name="proto.NodeStake.reward_rate",
            index=3,
            number=4,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="stake",
            full_name="proto.NodeStake.stake",
            index=4,
            number=5,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="stake_not_rewarded",
            full_name="proto.NodeStake.stake_not_rewarded",
            index=5,
            number=6,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="stake_rewarded",
            full_name="proto.NodeStake.stake_rewarded",
            index=6,
            number=7,
            type=3,
            cpp_type=2,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=192,
    serialized_end=346,
)

_NODESTAKEUPDATETRANSACTIONBODY.fields_by_name["end_of_staking_period"].message_type = timestamp__pb2._TIMESTAMP
_NODESTAKEUPDATETRANSACTIONBODY.fields_by_name["node_stake"].message_type = _NODESTAKE
DESCRIPTOR.message_types_by_name["NodeStakeUpdateTransactionBody"] = _NODESTAKEUPDATETRANSACTIONBODY
DESCRIPTOR.message_types_by_name["NodeStake"] = _NODESTAKE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NodeStakeUpdateTransactionBody = _reflection.GeneratedProtocolMessageType(
    "NodeStakeUpdateTransactionBody",
    (_message.Message,),
    {
        "DESCRIPTOR": _NODESTAKEUPDATETRANSACTIONBODY,
        "__module__": "node_stake_update_pb2"
        # @@protoc_insertion_point(class_scope:proto.NodeStakeUpdateTransactionBody)
    },
)
_sym_db.RegisterMessage(NodeStakeUpdateTransactionBody)

NodeStake = _reflection.GeneratedProtocolMessageType(
    "NodeStake",
    (_message.Message,),
    {
        "DESCRIPTOR": _NODESTAKE,
        "__module__": "node_stake_update_pb2"
        # @@protoc_insertion_point(class_scope:proto.NodeStake)
    },
)
_sym_db.RegisterMessage(NodeStake)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
